spring.application.name=rate-limiter-service
server.port=8080

# -----------------------------------------------------------------
# DOCKER CONFIGURATION
# We use 'redis' because that is the service name in docker-compose.yml
# -----------------------------------------------------------------
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.timeout=2s

# Enable reactive redis repositories (safe)
spring.data.redis.repositories.enabled=false

# ===============================
# WebFlux (important since you use Gateway)
# ===============================
spring.main.web-application-type=reactive

# ===============================
# Logging (useful for debugging)
# ===============================
logging.level.org.springframework.data.redis=INFO
logging.level.io.lettuce.core=INFO
logging.level.org.springframework.web=INFO

# ===============================
# Actuator (optional but recommended)
# ===============================
management.endpoint.health.show-details=always

spring.cloud.gateway.routes[0].id=target-application
spring.cloud.gateway.routes[0].uri=${TARGET_APP:http://localhost:3000}
spring.cloud.gateway.routes[0].predicates[0]=Path=/**

# Expose health, info, AND prometheus metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.server.port=8081
management.metrics.web.server.request.autotime.enabled=true
